### PR TITLE
Adjusted Analytics and Added Event Tracking

### PR DESCRIPTION
**Pull request by lindaicing**
uses "addEventListener" instead of "onclick" for popup.js functions.

Added "visitWebsite" ID for menu

Changed functions to Arrow Functions

http to https

Yeehaw

### CODE REVIEW

**Comment by lindaicing** [comment]
Uses "addEventListener" instead of "onclick" for popup.js functions.

**Comment by lindaicing** [comment]
@CubeOfCheese Separated files:

**/popup-scripts**
popup-norating.js - associated with popupNoRating.html
popup-notshop.js - associated with popupNotShop.html
popup-optin.js - associated with popupOptin.html
popup-shop.js - associated with popup.html

**Review by CubeOfCheese — APPROVED** [review]
_    |~  _
[_]---'--[_]
|'''|""`""|'''|
|  | /^\  |  |
|_|_|I|_|_|

**Comment by CubeOfCheese** [comment]
wow github really messed up my castle

**Pull request merged**
