### PR TITLE
Added badges to shops with no rating

### PR DESCRIPTION
**Pull request by lindaicing**
Added badges to shops with no rating

Fixed styling

Removed "sustainable production" sub-rating section

Changed popup window heights

### CODE REVIEW

**Comment by lindaicing** [comment]
With badges
Screen Shot 2020-06-23 at 2 08 39 AM

Without badges (new)
Screen Shot 2020-06-23 at 2 09 57 AM

Main Popup (new)
Screen Shot 2020-06-23 at 2 09 35 AM

**Comment by lindaicing** [comment]
Resized Popup with Badge
Screen Shot 2020-06-23 at 2 19 03 AM

No Badge (fixed sizing)
Screen Shot 2020-06-23 at 2 19 34 AM

**Comment by CubeOfCheese** [comment]
Is the background color still the reddish or the same as popup.html?

**Comment by lindaicing** [comment]
> Is the background color still the reddish or the same as popup.html?

What do you mean by background color?

**Comment by CubeOfCheese** [comment]
Sorry I just realized I could just check myself. The background color of popupNoData and popup looked different to me, but I think it's just the text color playing tricks on me. Never mind. Looks good!

**Pull request merged**
