### PR TITLE
Added and linked FAQ page

### PR DESCRIPTION
**Pull request by lindaicing**
Added and linked FAQ page to Website

Screen Shot 2020-07-19 at 8 11 56 PM
Screen Shot 2020-07-19 at 8 12 35 PM

### CODE REVIEW

**Comment by CubeOfCheese** [comment]
What does legally verified mean? I feel like that might not apply to all of the sources we use or end up using

**Comment by lindaicing** [comment]
> What does legally verified mean? I feel like that might not apply to all of the sources we use or end up using

I pulled the legal bit straight from BCorp's description, but I agree that it might not be the case for *every* source we use.
Screen Shot 2020-07-20 at 11 19 42 AM
What would be a better alternative? Would simply "verified" work?

**Comment by CubeOfCheese** [comment]
> > What does legally verified mean? I feel like that might not apply to all of the sources we use or end up using
> 
> @CubeOfCheese I pulled the legal bit straight from BCorp's description, but I agree that it might not be the case for _every_ source we use.
> Screen Shot 2020-07-20 at 11 19 42 AM
> What would be a better alternative? Would simply "verified" work?

The sources we'll use aren't all "verified" by any one group except us. We could say we use highly credible and respected sources.

**Comment by lindaicing** [comment]
@CubeOfCheese Fixed the wording!

Screen Shot 2020-07-20 at 11 53 46 AM

**Pull request merged**
