### PR TITLE
Updated "How To Use" Section

### PR DESCRIPTION
**Pull request by lindaicing**
Updated text and replaced placeholder image
Screen Shot 2020-06-12 at 7 11 19 PM

### CODE REVIEW

**Comment by lindaicing** [comment]
> We don't have permission from JC Penny to be using an image of their website like that so I'm not going to approve this. For now we either have to create a fake shopping page image which seems like a lot of work, or not feature that kind of "live" image at all. In the future we might be able to get permission from some ethical company

Sounds good! I’ll mock up a fake one tonight

**Comment by lindaicing** [comment]
Changed to fake shop
Screen Shot 2020-06-12 at 11 16 55 PM

**Comment by lindaicing** [comment]
ethicli-in-use

**Comment by CubeOfCheese** [comment]
Chef's Kiss

**Pull request merged**
