### PR TITLE
Fixed ad window height

### PR DESCRIPTION
**Pull request by lindaicing**
Screen Shot 2020-09-20 at 6 10 10 PM
Screen Shot 2020-09-20 at 6 10 27 PM
Screen Shot 2020-09-20 at 6 28 28 PM
Screen Shot 2020-09-20 at 6 10 52 PM

### CODE REVIEW

**Comment by lindaicing** [comment]
Screen Shot 2020-09-20 at 6 38 34 PM
Screen Shot 2020-09-20 at 6 38 44 PM

**Review by CubeOfCheese — CHANGES_REQUESTED** [review]
Tutorial machine broke

**Comment by lindaicing** [comment]
> Tutorial machine broke

Planning on fixing it in another PR, would that be ok?

**Review by CubeOfCheese — APPROVED** [review]
Good stuff

**Pull request merged**
