### PR TITLE
New badge format

### PR DESCRIPTION
**Pull request by lindaicing**
Updated badge format

Screen Shot 2020-09-19 at 12 46 57 AM
Screen Shot 2020-09-19 at 12 47 26 AM
Screen Shot 2020-09-19 at 12 47 12 AM
Screen Shot 2020-09-19 at 12 47 47 AM

### CODE REVIEW

**Comment by CubeOfCheese** [comment]
Do you think it should only display this way if there are more than 3 badges or something like that? Maybe it should display two of them without having to click to see them all. I'm not sure how it would pick which two to display though

**Comment by lindaicing** [comment]
> Do you think it should only display this way if there are more than 3 badges or something like that? Maybe it should display two of them without having to click to see them all. I'm not sure how it would pick which two to display though

Yeah that can be done! It currently tracks the number of badges using a badge counter so I can change it to have the format only if there's more than 3 badges

**Comment by lindaicing** [comment]
Up to 3 badges shows this:
Screen Shot 2020-09-19 at 11 36 52 AM

**Comment by lindaicing** [comment]
Screen Shot 2020-09-19 at 9 23 42 PM
Screen Shot 2020-09-19 at 9 23 55 PM

**Review by CubeOfCheese — APPROVED** [review]
I'm so excited about this. It looks so cool

**Pull request merged**
