### PR TITLE
Added BLM badges with tooltips

### PR DESCRIPTION
**Pull request by lindaicing**
BLM and Black-Owned Business badges added. Adjusted badge padding. Tooltips (text that shows on hover) also added.

### CODE REVIEW

**Comment by lindaicing** [comment]
The mouse isn't shown in the screencaptures
Screen Shot 2020-06-15 at 2 01 52 AM
Screen Shot 2020-06-15 at 2 01 44 AM
Screen Shot 2020-06-15 at 2 01 38 AM
Screen Shot 2020-06-15 at 2 01 31 AM

**Comment by CubeOfCheese** [comment]
The descriptions seem so concise that they don't actually offer more clarity except for the BLM badge

**Comment by lindaicing** [comment]
> The descriptions seem so concise that they don't actually offer more clarity except for the BLM badge

Do you think we should make more concise descriptions or remove them entirely?

**Comment by CubeOfCheese** [comment]
No I think the descriptions should be _less_ concise

**Comment by lindaicing** [comment]
Screen Shot 2020-06-17 at 5 57 53 PM
Screen Shot 2020-06-17 at 5 58 13 PM
Screen Shot 2020-06-17 at 5 58 42 PM
Screen Shot 2020-06-17 at 5 58 56 PM

**Pull request merged**
